# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "My JupyterBook"
author: "Jezzel Faith Q. Gier"
logo: "logo.png"

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: force

# Define the name of the LaTeX output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file for citations
bibtex_bibfiles:
  - references.bib

# Repository configuration
repository:
  url: "https://github.com/jezzelgier/my-jupyter-book"   # Update with your actual repo link
  path_to_book: "docs"
  branch: "main"

# HTML configuration
html:
  use_issues_button: true
  use_repository_button: true
  favicon: "favicon.ico"   # Add a small icon if you have one
  home_page_in_navbar: true
  comments:
    hypothesis: false
    utterances:
      repo: "jezzelgier/my-jupyter-book"
      theme: "github-light"
      issue-term: "pathname"
  announcement: "🚀 Welcome to my JupyterBook! Explore notes, projects, and ideas."

# Launch button settings
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com/"
  binderhub_url: "https://mybinder.org"
  thebe: true

# Theme customization
sphinx:
  config:
    html_theme_options:
      use_download_button: true
      navigation_depth: 4
      show_nav_level: 2
      repository_url: "https://github.com/jezzelgier/my-jupyter-book"
      repository_branch: "main"
      path_to_docs: "docs"
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
      extra_navbar: |
        <p><a href="https://github.com/Jzelfthr" target="_blank">🌐 GitHub</a> | 
        <a href="https://www.linkedin.com/in/jezzel-faith-gier" target="_blank">💼 LinkedIn</a> | 
        <a href="https://www.instagram.com/jzelfthr/" target="_blank">📸 Instagram</a></p>
      extra_footer: |
        <p>Made with ❤️ by <strong>Jezzel Faith Q. Gier</strong><br>
        Powered by <a href="https://jupyterbook.org" target="_blank">JupyterBook</a></p>
