# Book settings
title: "Deep Learning Portfolio"
author: "Jezzel Faith Q. Gier"
logo: "logo.png"

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: "https://github.com/Jzelfthr/DL_Portfolio"
  path_to_book: ""
  branch: "main"

html:
  favicon: "favicon.ico"
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: true
  comments:
    hypothesis: false
  announcement: "🚀 Welcome to my Deep Learning Portfolio — Explore Labs, Exercises, and Projects!"
  extra_footer: |
    <p>Made with ❤️ by <strong>Jezzel Faith Q. Gier</strong><br>
    Hosted on <a href="https://github.com/Jzelfthr/DL_Portfolio" target="_blank">GitHub Pages</a></p>

launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com/"
  binderhub_url: "https://mybinder.org"
  thebe: true

sphinx:
  config:
    html_theme_options:
      navigation_depth: 4
      show_nav_level: 2
      use_download_button: true
      repository_url: "https://github.com/Jzelfthr/DL_Portfolio"
      repository_branch: "main"
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
      extra_navbar: |
        <p><a href="https://github.com/Jzelfthr" target="_blank">🌐 GitHub</a> |
        <a href="https://www.linkedin.com/in/jezzel-faith-gier" target="_blank">💼 LinkedIn</a> |
        <a href="https://www.instagram.com/jzelfthr" target="_blank">📸 Instagram</a></p>
